# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compra.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 320)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 10, 381, 311))
        self.label.setStyleSheet("image: url(:/iconogotamas/g107.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(390, 240, 71, 61))
        self.label_4.setStyleSheet("image: url(:/iconoNubeBlanco/g982.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.lblStatus = QtWidgets.QLabel(Form)
        self.lblStatus.setGeometry(QtCore.QRect(60, 30, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblStatus.setFont(font)
        self.lblStatus.setObjectName("lblStatus")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(190, 180, 101, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(80, 130, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lblLitrosDisponibles = QtWidgets.QLabel(Form)
        self.lblLitrosDisponibles.setGeometry(QtCore.QRect(320, 130, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblLitrosDisponibles.setFont(font)
        self.lblLitrosDisponibles.setObjectName("lblLitrosDisponibles")
        self.lblInfoComp = QtWidgets.QLabel(Form)
        self.lblInfoComp.setGeometry(QtCore.QRect(60, 80, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblInfoComp.setFont(font)
        self.lblInfoComp.setObjectName("lblInfoComp")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lblStatus.setText(_translate("Form", "se realizo la compra exitosamente"))
        self.pushButton.setText(_translate("Form", "Aceptar"))
        self.label_3.setText(_translate("Form", "Tu saldo actual es de: "))
        self.lblLitrosDisponibles.setText(_translate("Form", "9999"))
        self.lblInfoComp.setText(_translate("Form", "se realizo la compra exitosamente"))
import icons.iconos_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
