# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InformacionCliente(object):
    def setupUi(self, InformacionCliente):
        InformacionCliente.setObjectName("InformacionCliente")
        InformacionCliente.resize(480, 320)
        font = QtGui.QFont()
        font.setPointSize(12)
        InformacionCliente.setFont(font)
        self.label = QtWidgets.QLabel(InformacionCliente)
        self.label.setGeometry(QtCore.QRect(86, 40, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.nombreCliente = QtWidgets.QLabel(InformacionCliente)
        self.nombreCliente.setGeometry(QtCore.QRect(160, 40, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nombreCliente.setFont(font)
        self.nombreCliente.setObjectName("nombreCliente")
        self.label_3 = QtWidgets.QLabel(InformacionCliente)
        self.label_3.setGeometry(QtCore.QRect(40, 110, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.saldoDisponible = QtWidgets.QLCDNumber(InformacionCliente)
        self.saldoDisponible.setGeometry(QtCore.QRect(250, 110, 121, 51))
        self.saldoDisponible.setObjectName("saldoDisponible")
        self.label_4 = QtWidgets.QLabel(InformacionCliente)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 391, 301))
        self.label_4.setStyleSheet("image: url(:/iconogotamas/g107.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.botonDespachar = QtWidgets.QPushButton(InformacionCliente)
        self.botonDespachar.setGeometry(QtCore.QRect(70, 200, 100, 90))
        self.botonDespachar.setObjectName("botonDespachar")
        self.botonCancelar = QtWidgets.QPushButton(InformacionCliente)
        self.botonCancelar.setGeometry(QtCore.QRect(280, 200, 100, 90))
        self.botonCancelar.setObjectName("botonCancelar")
        self.label_5 = QtWidgets.QLabel(InformacionCliente)
        self.label_5.setGeometry(QtCore.QRect(400, 240, 70, 60))
        self.label_5.setStyleSheet("image: url(:/iconoNubeBlanco/g982.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_4.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.nombreCliente.raise_()
        self.saldoDisponible.raise_()
        self.botonDespachar.raise_()
        self.botonCancelar.raise_()
        self.label_5.raise_()

        self.retranslateUi(InformacionCliente)
        QtCore.QMetaObject.connectSlotsByName(InformacionCliente)

    def retranslateUi(self, InformacionCliente):
        _translate = QtCore.QCoreApplication.translate
        InformacionCliente.setWindowTitle(_translate("InformacionCliente", "Form"))
        self.label.setText(_translate("InformacionCliente", "Hola"))
        self.nombreCliente.setText(_translate("InformacionCliente", "nombre cliente"))
        self.label_3.setText(_translate("InformacionCliente", "Saldo disponible"))
        self.botonDespachar.setText(_translate("InformacionCliente", "Despachar"))
        self.botonCancelar.setText(_translate("InformacionCliente", "Cancelar"))
import icons.iconos_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InformacionCliente = QtWidgets.QWidget()
    ui = Ui_InformacionCliente()
    ui.setupUi(InformacionCliente)
    InformacionCliente.show()
    sys.exit(app.exec_())
