# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'webCam.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 320)
        Form.setMinimumSize(QtCore.QSize(480, 320))
        Form.setMaximumSize(QtCore.QSize(480, 320))
        self.lblWebcam = QtWidgets.QLabel(Form)
        self.lblWebcam.setGeometry(QtCore.QRect(10, 50, 351, 261))
        self.lblWebcam.setText("")
        self.lblWebcam.setObjectName("lblWebcam")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(400, 240, 71, 61))
        self.label.setStyleSheet("image: url(:/iconoNubeBlanco/g982.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.botonCancelar = QtWidgets.QPushButton(Form)
        self.botonCancelar.setGeometry(QtCore.QRect(370, 110, 100, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.botonCancelar.setFont(font)
        self.botonCancelar.setObjectName("botonCancelar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Pon tu codigo QR frente a la camara!!"))
        self.botonCancelar.setText(_translate("Form", "Cancelar"))
import icons.iconos_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
